# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mod14
spec:
  selector:
    matchLabels:
      app: mod14
  replicas: 1
  template:
    metadata:
      labels:
        app: mod14
    spec:
      containers:
      - name: todo-app
        image: todo-app:prod
        ports:
        - containerPort: 8000       
        imagePullPolicy: Never